plugins {
    id 'com.android.application'
}

android {
    namespace 'uk.co.sperinservices.certificates'
    compileSdk 35

    signingConfigs {
        stable {
            storeFile file(System.getProperty("user.home") + "/.android/sperin-certificates-stable.jks")
            storePassword "android"
            keyAlias "sperincertificates"
            keyPassword "android"
        }
    }

    defaultConfig {
        applicationId 'uk.co.sperinservices.certificates.stable'
        minSdk 26
        targetSdk 35
        versionCode 141
        versionName '1.4.1'
    }

    buildTypes {
        debug {
            debuggable true
            signingConfig signingConfigs.stable
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.stable
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
