plugins {
    id 'com.android.application'
}

android {
    namespace 'uk.co.sperinservices.certificates'
    compileSdk 35

    defaultConfig {
        applicationId 'uk.co.sperinservices.certificates'
        minSdk 26
        targetSdk 35
        versionCode 120
        versionName '1.2.0'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
