/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as LeaveAReviewRouteImport } from './routes/leave-a-review'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommercialRouteImport } from './routes/commercial'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesTestingRouteImport } from './routes/services.testing'
import { Route as ServicesSmartHomeRouteImport } from './routes/services.smart-home'
import { Route as ServicesRewiresRouteImport } from './routes/services.rewires'
import { Route as ServicesKitchensBathroomsRouteImport } from './routes/services.kitchens-bathrooms'
import { Route as ServicesEvChargersRouteImport } from './routes/services.ev-chargers'
import { Route as ServicesConsumerUnitsRouteImport } from './routes/services.consumer-units'
import { Route as OurWorkSlugRouteImport } from './routes/our-work.$slug'

const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveAReviewRoute = LeaveAReviewRouteImport.update({
  id: '/leave-a-review',
  path: '/leave-a-review',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialRoute = CommercialRouteImport.update({
  id: '/commercial',
  path: '/commercial',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesTestingRoute = ServicesTestingRouteImport.update({
  id: '/services/testing',
  path: '/services/testing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSmartHomeRoute = ServicesSmartHomeRouteImport.update({
  id: '/services/smart-home',
  path: '/services/smart-home',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRewiresRoute = ServicesRewiresRouteImport.update({
  id: '/services/rewires',
  path: '/services/rewires',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesKitchensBathroomsRoute =
  ServicesKitchensBathroomsRouteImport.update({
    id: '/services/kitchens-bathrooms',
    path: '/services/kitchens-bathrooms',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesEvChargersRoute = ServicesEvChargersRouteImport.update({
  id: '/services/ev-chargers',
  path: '/services/ev-chargers',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesConsumerUnitsRoute = ServicesConsumerUnitsRouteImport.update({
  id: '/services/consumer-units',
  path: '/services/consumer-units',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkSlugRoute = OurWorkSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => OurWorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/leave-a-review': typeof LeaveAReviewRoute
  '/our-work': typeof OurWorkRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/services/consumer-units': typeof ServicesConsumerUnitsRoute
  '/services/ev-chargers': typeof ServicesEvChargersRoute
  '/services/kitchens-bathrooms': typeof ServicesKitchensBathroomsRoute
  '/services/rewires': typeof ServicesRewiresRoute
  '/services/smart-home': typeof ServicesSmartHomeRoute
  '/services/testing': typeof ServicesTestingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/leave-a-review': typeof LeaveAReviewRoute
  '/our-work': typeof OurWorkRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/services/consumer-units': typeof ServicesConsumerUnitsRoute
  '/services/ev-chargers': typeof ServicesEvChargersRoute
  '/services/kitchens-bathrooms': typeof ServicesKitchensBathroomsRoute
  '/services/rewires': typeof ServicesRewiresRoute
  '/services/smart-home': typeof ServicesSmartHomeRoute
  '/services/testing': typeof ServicesTestingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/commercial': typeof CommercialRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/gallery': typeof GalleryRoute
  '/leave-a-review': typeof LeaveAReviewRoute
  '/our-work': typeof OurWorkRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/reviews': typeof ReviewsRoute
  '/our-work/$slug': typeof OurWorkSlugRoute
  '/services/consumer-units': typeof ServicesConsumerUnitsRoute
  '/services/ev-chargers': typeof ServicesEvChargersRoute
  '/services/kitchens-bathrooms': typeof ServicesKitchensBathroomsRoute
  '/services/rewires': typeof ServicesRewiresRoute
  '/services/smart-home': typeof ServicesSmartHomeRoute
  '/services/testing': typeof ServicesTestingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/commercial'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/leave-a-review'
    | '/our-work'
    | '/privacy'
    | '/reviews'
    | '/our-work/$slug'
    | '/services/consumer-units'
    | '/services/ev-chargers'
    | '/services/kitchens-bathrooms'
    | '/services/rewires'
    | '/services/smart-home'
    | '/services/testing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/commercial'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/leave-a-review'
    | '/our-work'
    | '/privacy'
    | '/reviews'
    | '/our-work/$slug'
    | '/services/consumer-units'
    | '/services/ev-chargers'
    | '/services/kitchens-bathrooms'
    | '/services/rewires'
    | '/services/smart-home'
    | '/services/testing'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/commercial'
    | '/contact'
    | '/faqs'
    | '/gallery'
    | '/leave-a-review'
    | '/our-work'
    | '/privacy'
    | '/reviews'
    | '/our-work/$slug'
    | '/services/consumer-units'
    | '/services/ev-chargers'
    | '/services/kitchens-bathrooms'
    | '/services/rewires'
    | '/services/smart-home'
    | '/services/testing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CommercialRoute: typeof CommercialRoute
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  GalleryRoute: typeof GalleryRoute
  LeaveAReviewRoute: typeof LeaveAReviewRoute
  OurWorkRoute: typeof OurWorkRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ReviewsRoute: typeof ReviewsRoute
  ServicesConsumerUnitsRoute: typeof ServicesConsumerUnitsRoute
  ServicesEvChargersRoute: typeof ServicesEvChargersRoute
  ServicesKitchensBathroomsRoute: typeof ServicesKitchensBathroomsRoute
  ServicesRewiresRoute: typeof ServicesRewiresRoute
  ServicesSmartHomeRoute: typeof ServicesSmartHomeRoute
  ServicesTestingRoute: typeof ServicesTestingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave-a-review': {
      id: '/leave-a-review'
      path: '/leave-a-review'
      fullPath: '/leave-a-review'
      preLoaderRoute: typeof LeaveAReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial': {
      id: '/commercial'
      path: '/commercial'
      fullPath: '/commercial'
      preLoaderRoute: typeof CommercialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/testing': {
      id: '/services/testing'
      path: '/services/testing'
      fullPath: '/services/testing'
      preLoaderRoute: typeof ServicesTestingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/smart-home': {
      id: '/services/smart-home'
      path: '/services/smart-home'
      fullPath: '/services/smart-home'
      preLoaderRoute: typeof ServicesSmartHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/rewires': {
      id: '/services/rewires'
      path: '/services/rewires'
      fullPath: '/services/rewires'
      preLoaderRoute: typeof ServicesRewiresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/kitchens-bathrooms': {
      id: '/services/kitchens-bathrooms'
      path: '/services/kitchens-bathrooms'
      fullPath: '/services/kitchens-bathrooms'
      preLoaderRoute: typeof ServicesKitchensBathroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ev-chargers': {
      id: '/services/ev-chargers'
      path: '/services/ev-chargers'
      fullPath: '/services/ev-chargers'
      preLoaderRoute: typeof ServicesEvChargersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/consumer-units': {
      id: '/services/consumer-units'
      path: '/services/consumer-units'
      fullPath: '/services/consumer-units'
      preLoaderRoute: typeof ServicesConsumerUnitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work/$slug': {
      id: '/our-work/$slug'
      path: '/$slug'
      fullPath: '/our-work/$slug'
      preLoaderRoute: typeof OurWorkSlugRouteImport
      parentRoute: typeof OurWorkRoute
    }
  }
}

interface OurWorkRouteChildren {
  OurWorkSlugRoute: typeof OurWorkSlugRoute
}

const OurWorkRouteChildren: OurWorkRouteChildren = {
  OurWorkSlugRoute: OurWorkSlugRoute,
}

const OurWorkRouteWithChildren =
  OurWorkRoute._addFileChildren(OurWorkRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CommercialRoute: CommercialRoute,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  GalleryRoute: GalleryRoute,
  LeaveAReviewRoute: LeaveAReviewRoute,
  OurWorkRoute: OurWorkRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ReviewsRoute: ReviewsRoute,
  ServicesConsumerUnitsRoute: ServicesConsumerUnitsRoute,
  ServicesEvChargersRoute: ServicesEvChargersRoute,
  ServicesKitchensBathroomsRoute: ServicesKitchensBathroomsRoute,
  ServicesRewiresRoute: ServicesRewiresRoute,
  ServicesSmartHomeRoute: ServicesSmartHomeRoute,
  ServicesTestingRoute: ServicesTestingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
